export const ANALYTICS_BRAND_FALLBACKS = [
  {
    id: 'mgc',
    name: 'MGC Coin',
    symbol: 'MGC',
    logoUrl: '/brands/mgc-coin-logo.png',
    footerLogoUrl: '/brands/mgc-footer-logo.svg',
    footer: 'metagamescoin.io',
    domain: 'metagamescoin.io',
    chartColor: '#d9b91d',
    theme: {
      background: '#050606',
      backgroundAlt: '#262000',
      surface: '#111315',
      surfaceAlt: '#1c1d1e',
      text: '#fffdf5',
      muted: '#aaa797',
      positive: '#1fd083',
      negative: '#ef5350',
      accent: '#f0c419',
      accentAlt: '#b88a16',
      border: '#64551c',
    },
    motifs: ['signal-yellow horizon', 'restrained gold light', 'black editorial field', 'precise market grid'],
    market: {
      provider: 'geckoterminal',
      network: 'bsc',
      contract: '0xbb73BB2505AC4643d5C0a99c2A1F34B3DfD09D11',
      poolName: 'RZ / MGC',
      tokenSide: 'quote',
    },
  },
  {
    id: 'oasis',
    name: 'Oasis Coin',
    symbol: 'OASIS',
    logoUrl: '/brands/oasis-coin-logo.png',
    footerLogoUrl: '/brands/oasis-footer-logo.svg',
    footer: 'rzoasis.tech',
    domain: 'rzoasis.tech',
    chartColor: '#739e90',
    theme: {
      background: '#060708',
      backgroundAlt: '#20242a',
      surface: '#12151a',
      surfaceAlt: '#1d2229',
      text: '#f5f6f7',
      muted: '#9ba2aa',
      positive: '#28c890',
      negative: '#df6d69',
      accent: '#aeb8c4',
      accentAlt: '#4d8f7c',
      border: '#454c55',
    },
    motifs: ['lunar silver arc', 'graphite city grid', 'emerald data pulse', 'orbital precision'],
    market: {
      provider: 'geckoterminal',
      network: 'bsc',
      contract: '0x1a4D41219C547f3A0EE36cf3d9E68F80699cF283',
      poolName: 'OASIS / MGC',
      tokenSide: 'base',
    },
  },
  {
    id: 'jewelry',
    name: 'Jewelry Coin',
    symbol: 'JEWELRY',
    logoUrl: '/brands/jewelry-coin-logo.png',
    footerLogoUrl: '/brands/jewelry-footer-logo.svg',
    footer: 'Jewelry.Game',
    domain: 'Jewelry.Game',
    chartColor: '#8f82e8',
    theme: {
      background: '#f8f5ff',
      backgroundAlt: '#d8cbff',
      surface: '#ffffff',
      surfaceAlt: '#eee8ff',
      text: '#201348',
      muted: '#706a82',
      positive: '#2ba780',
      negative: '#cf5b78',
      accent: '#8f72ed',
      accentAlt: '#d68add',
      border: '#c9bdf0',
    },
    motifs: ['crystal refraction', 'platinum ring', 'lavender glass', 'soft pearl light'],
    market: {
      provider: 'geckoterminal',
      network: 'bsc',
      contract: '0xf04FaB6Dda66261eaBfD65e92A6b81dDaF6a950a',
      poolName: 'Jewelry / MGC',
      tokenSide: 'base',
    },
  },
  {
    id: 'industrial',
    name: 'Industrial Token',
    symbol: 'INDUSTRIAL',
    logoUrl: '/brands/industrial-coin-logo.png',
    footerLogoUrl: '/brands/industrial-footer-logo.png',
    footer: 'industrial.game',
    domain: 'industrial.game',
    chartColor: '#b56ad9',
    theme: {
      background: '#10072d',
      backgroundAlt: '#291050',
      surface: '#191231',
      surfaceAlt: '#281a47',
      text: '#f8f5ff',
      muted: '#b9aed1',
      positive: '#41c98d',
      negative: '#ef6c75',
      accent: '#f4c224',
      accentAlt: '#7816d2',
      border: '#6c42a1',
    },
    motifs: ['precision gold robotics', 'industrial violet horizon', 'verified light paths', 'real-economy infrastructure'],
    market: {
      provider: 'geckoterminal',
      network: 'bsc',
      contract: '0x9e06e1203bdc3747ee3ab5fa9488619bcf2a2666',
      poolName: 'Industrial / MGC',
      tokenSide: 'base',
    },
  },
]

export const ANALYTICS_MEDIA_ROWS = ANALYTICS_BRAND_FALLBACKS.map(item => ({
  m: item.name,
  color: item.chartColor,
  abbr: item.symbol.slice(0, 3),
  logo: item.logoUrl,
  sub: `Verified ${item.name} market`,
}))
